apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:toNZb6Q8XE/q0SeLjTHtUZgOGdJrhTCKa4HRnPNYqmPz6ngTaWPo+A==,iv:hxTwEBUB93tbUlW1e2sk0COfVkCP4qsgxlyQIPXTORo=,tag:mjvHZZ/bH3/uvtXyCo1yzQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QnNrazlnYXBZclIwWkhH
        YWlOeGJKNHU1UURyTkRKdFdwcWtXZW9mcjJrCk5KMzBDaHF6ZUtyS3pqdm55MDV4
        dkpObGJCUlozT3IrblVQcjdOV284cW8KLS0tIFJ5UDUxYm5mV1hjRC9oN29VVko4
        b2tUTlZqak5ZK3N2dmQzaFM5QzNra3cKK/sh9jf73/yTL823+HivLwSF8tcrPYNO
        ZOnDPrM9aKEmrwT4//WOre3dcaHP59Ow7bNZcFfJb6CAh7XSD37+ug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1az600w93g3yt7kc4qwd0u0uvkaj9jwfz2xsdpkfj036qgjvly42saj0t40
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T18:04:59Z"
  mac: ENC[AES256_GCM,data:RXM7G24UXKHMuaUdpFjQb2Pw7TN4VG3QQzw1pAI0MJDqCVrkuekiy7NMt7vycoykZw4uP3z8cbZ1sejDISsuautzPFzg64Lce4G1hQmFmkhP6XvmCyuZCgVuMjV8ywsoYYG8/zlsdwblwNFrnTz/U0rXLr5SWjmPIjplRBKAKWg=,iv:eSa9hBwhW6oQLn7oH3ufAp7lyTF5uG0yp3zMIMgwqd8=,tag:utC25/BSMXOHto11N4kboA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
