apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:lLmA0x8r+M3I8yQ=,iv:t+cCqdOnqWrrI8NfnZZshRJ0z7KR2p05TwZdm7VZMy0=,tag:sAENVt2nHqZLF5Nhm+BH/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcHo5RWZQVWtockRwMU15
        dmIrT05EWHB3MndQVG94TVRXSlh1Uk93QUhnClpXcUdYLy9PYVlCaFJiK3QvZStZ
        SmlISE96SkhpVk1sRzlGY2dCaEVXekEKLS0tIHAwQjdWZW9kNkFqZDJ0YXhYWnlR
        bCtQN0Vpa0lQMmRPM3JsdklhYTJlNmsKo074d940Ec91mxO4RYKROxKyuyRMerry
        lBVVwGYmfGM0tkEiIDYOqB4V8MkYm3/ol046ol+0JDD0We3ECQ0t4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1az600w93g3yt7kc4qwd0u0uvkaj9jwfz2xsdpkfj036qgjvly42saj0t40
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T18:04:58Z"
  mac: ENC[AES256_GCM,data:yS7oe9UHlS7Cx1l1fDPYMg1z1HCa/AjaC8vBgLAkf3230OQ3T+d5Z2tP4/OsLAu30VttKSQUIJaEjnNOKFx6mZDNgNKZZ9hfhpE+u73OP8d6nc3mHrO1Rc4H4iVJBEr3cr/A/y3aqyNW/YRpgDnsMqwWOv4GpDWGe/mPYEih1Yo=,iv:mZ6DxDoSQjjYWsQeBkKznAXyNWkPbF5R+ivmckTKmAQ=,tag:zx/GDJ/JSoizvr/mKygTfg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
