apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:hxQMtU6oWIlSDapTMgkrw6EBVNXSL+ul9tyXRlTrv7s=,iv:ZOcX3xB/+TPg6/5lnL0e3LGnQo2pYHHDpGUjQ9VgNfY=,tag:ibyT2O4yRM3GYxWBdtmJjA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR25PN0VqS295cWhWUHdk
        TVlTbDJmd05ub3NlZDU4ZXdKUWp0WkFsZEdjCnVSMDZBVVA2dFp1d0hQcEcvdDJn
        b0NQNDgwL29BMVlYNFFRZUI5QkE0M2cKLS0tIEp1U1hvYkZaTVcvS3N4UWc0Qk5S
        TnhzNHJrQVEvT1p1ZndqcFEveGRxSXMKnS58ge0nEVOAcDIMnFtWJZCbOWQmXNTP
        qlhVckVdz8xFNnEHMALSZEvKmrLhhWhO1Ey/m5BPimZ/7DLw6RMaZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1az600w93g3yt7kc4qwd0u0uvkaj9jwfz2xsdpkfj036qgjvly42saj0t40
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T18:04:58Z"
  mac: ENC[AES256_GCM,data:nnZEv8Vbbw2xXzmiD+OwTRse2V6eVCfrYpjxs9zc2ar3wQsqDDjrHDevAa7mR+KnIZnBqMBBd86o7t1fJJutqu2rJxwIU2rM7dE8iLr0htAvmvSeCQ9sbw1V+M5ZSKT3+E5QGyRfhy2nfiTu5Kxj2Zp12xH/q5o1tOgSKUSAfA8=,iv:EsL8WCWIAE6OZ5JOoFDJaRkKA18VRyUqmn6iFSz2QXY=,tag:eLHmn3gi+jUjHfQpM5uMgw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
