apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:arnHZyw9Xmo+GFiEUGuuubsMh8syMVcpqD76dLr6BemogFvmzHS2Y3xUzcI4E+euRc2xu+eb+lfTFDA2vs4IS/jQVOops7IjkV5zak2qvML/xa//94wrD1+dR0SJLaEIleK5rSkqFpU2/aZYiNIr1v23nsRps5St0fQ4B1sJ9XicBYHpx9gmBuLZLCpJKBu7HgykHCFFPTzjy8Tjn9Vd9Td9tpbfQ6RSeo/UnutmbcN6PhJz,iv:Prty2tbQbrp5rad0u8LbUVn/w4LaWLQFyTGm7eykb5g=,tag:tJNC3IUR67iX+11mXU4uSA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdnBxVFBLV3h6UUhWVlc0
        SU5ncGZEQVlDL3NadEVrK2ZYdlEzbElQOUFrCk5iR2MyY2VVRlFRbjRVdnB1elVt
        NUpMVFk3a2FGb1ZFN0g0d3ROREcvakEKLS0tIHJLY2F1MGlQYXo5R0lxS3dsVUJs
        L3NJL1B3UUlwMUdjbGkydVBZT1hVWXcK+6h8J4HF25WvsnXgSpWhFbn68UGVh16M
        7BP/O09oo1ZBFCotJYSDX90ekwCjoNKyFOJM3tb/P+qxkkGlUcaaWw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1az600w93g3yt7kc4qwd0u0uvkaj9jwfz2xsdpkfj036qgjvly42saj0t40
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T18:04:59Z"
  mac: ENC[AES256_GCM,data:6xDn1C6j5ESteDXRYbqoKK0xQ1IzCd3JFaPsycidRFH2M43RCXPZ57/Ep3cAPLCYbRX3JDuQ8Dm+Yz9I346l3DpHpmBsxZYwZ2G5l18BW90SwBcBAAhtvw4yktHhhjsUlfxndDS5VVVNRWOnqT8vfIZY2qRR4lalHlVoPi1sft0=,iv:S0sM4eVZB7U9Daxcely72iHLczcUH28KQ1OZbiO5ORc=,tag:tzi/7HYCU6HMgabzsa7JMg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
