apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:i43viy10ukkKF9TMUdXKSB+CtGWj2kmpjHGeAuQ1G1nvcaJ9ShPjXg==,iv:l7tOsv7SBu10IzgbWpa/VCfzgMmuCK9mEt9LhrhCtZ8=,tag:J2rlw5tXO3MJ5znn0yfgEg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbnZ4Z1daQkxiRUVCNmhE
        L0xmNE5MNm5WN2N3N2pCNW50aC9idDRJR200Cllzdi9IdGdBbWF0bjluNGpuTEcy
        c29xUnFOQ1lGZGU2bytwcEFuK2oyamcKLS0tIFVEeStGcVBpZ0VyUDQ3WlI1SU5T
        bERWdzI4bnA0dThQU1FxNXNlNjZQcE0KEc1o53twV9Az1P3BfPSqxmYsJV7hhg+y
        0JE2t1qPNtydJcgWepqm+TXw2M1JqsK0vgjOxy4xg8K0Jgrx4vPStg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1az600w93g3yt7kc4qwd0u0uvkaj9jwfz2xsdpkfj036qgjvly42saj0t40
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T18:04:58Z"
  mac: ENC[AES256_GCM,data:ItDmdIayMEIu4Uhyyz8LkxpdNpQTJXXADVyXHamfomD7sTdTJNB1yL/bjR3o8z8Bpv+f2nxWH6VHkZ71t23KzX9avmRjRF1By4QmQM/B84Modss8/4uT5b8JqSLEGJ2VrPqflcQLt3nhdJ6xcWaCz4TCd0Ssjh6OJjcjO2oKZOg=,iv:j3iY2bU72axyw2Gx6iz1eZtTG2vTsB4k6P1f1aMea7g=,tag:5HqKpL00VmQuXZK0BFhTpw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
